name: Docs Linting

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  docs-linting:
    uses: faraaz-bot/rocm-docs-core/.github/workflows/linting.yml@develop
